### ISSUE TITLE
Lets take this even further

### ISSUE THREAD

**Issue by adamearle** [cogitas3d/OrtogOnBlender#1]
If we combine this with tracking it could potentially lead to the Blender version of Equalizer 3D.
We were using Equalizer 3D in Animal Logic and it is used heavily there on a day to day basis. They just finished off https://www.youtube.com/watch?v=7Pa_Weidt08. 

I tried to get them to use Blender but unfortunately, it's hard to teach young dogs new tricks when all they can see is the bone.  My understanding, most studios are using  3D Equalizer though I would love to see this idea pushed into Blender

So here are some thoughts and things for you to think about:
1. 3D Equalizer is just a big calculator like all tracking software its simple calculator
2. Think automation
3. Blam addon:  Capturing the camera information for tracking for when you don't have the lens detail
       Github:  https://github.com/stuffmatic/blam
       YouTube video of how it works:  https://www.youtube.com/watch?v=yeWzQYh7iH0

      Perhaps get in contact with this developer?

4. An animated moving camera (not lens zoom): using Blam and taking the averages over a range of different keyframes will help create more accurate lense data that could potentially be used to establish better-animated keyframe data.
5. Automate a camera from where the camera was shot from (This kinda of information works well when sending it off to the matte painters).
6. Coloured point cloud information for fast visualization of the 3D geo that is created this could be created with particle systems with no physics that last the length of the movie that is being tracked and creating the photogrammetry Geometry
7. Here are some 3D Equalizer tutorials that will to school you up on some of what I am talking about:   https://www.3dequalizer.com/?site=tutorials

WOW man this is really inspiring work. I'd also love to encourage you to be apart of the Google+ community there are a lot of great developers on there. 
 
https://plus.google.com/communities/115632807910317842467

**Comment by cogitas3d** [comment]
Hi @adamearle!

Interesting, I think I understood what you want to do, I make some experiences some yeras ago with tracking + photogrammetry: 

![captura-de-tela-de-2013-11-26-161535-1024x576](https://user-images.githubusercontent.com/2422483/33812619-6cf9c0be-ddfd-11e7-80e1-a6b9b4411a06.png)

![img_4_sharpen](https://user-images.githubusercontent.com/2422483/33812649-9b901248-ddfd-11e7-9c11-40a2e044caf8.png)

1) http://www.ciceromoraes.com.br/blog/?p=1461 (in Portuguese)

2) https://www.youtube.com/watch?v=UGnY5nfBbeE

And I think what you need it a program that capture the camera position and put inside Blender, happyly it exist, and you can use .OUT file created by OpenMVG: http://koelzk.crispy-cow.de/article/9/importing-bundler-scenes-to-blender

A big hug!
