### ISSUE TITLE
no sensor_width_camera_database.txt

### ISSUE THREAD

**Issue by zoggi02** [cogitas3d/OrtogOnBlender#10]
![image](https://user-images.githubusercontent.com/19963440/52160390-64166180-26e7-11e9-8eff-f6d59d5d8d05.png)

**Comment by cogitas3d** [comment]
Hi @zoggi02 !

How do you install OrtogOnBlender?

The next version doesnt have this error anymore, unless you used other image (not jpg) or .jpeg (not work) or the jpeg is not a camera file.

A big hug!
