### ISSUE TITLE
Error running the addon

### ISSUE THREAD

**Issue by jppradoesousa** [cogitas3d/OrtogOnBlender#11]
Can´t run the Addon, unfortunately

My blender version: 2.79

Hope I can get some help, thanks :)

[OrtogOnBlender_error.zip](https://github.com/cogitas3d/OrtogOnBlender/files/2832951/OrtogOnBlender_error.zip)

**Comment by cogitas3d** [comment]
Hi @jppradoesousa !

What is your Operating System?

**Comment by jppradoesousa** [comment]
Hi Cícero!!

I appreciate your help, actually you are already helping me by WhatsApp 😁

I am the one who's just sent you a message...

The installation is going on, here. I'll get back to you as soon as it finishes.

Thanks a lot!!!

João Paulo Sousa


Em 5 de fev de 2019 15:26, Cicero Moraes <notifications@github.com> escreveu:

Hi @jppradoesousa<https://github.com/jppradoesousa> !

What is your Operating System?

**Comment by cogitas3d** [comment]
Ah, OK :D

The link to install on Windows: http://www.ciceromoraes.com.br/doc/pt_br/OrtogOnBlender/Instalacao_Windows.html

A big hug!

**Comment by basharbme** [comment]
helo,
I have error operating the addon and need help
My blender version is 2.78

**Comment by basharbme** [comment]
It worked !
