### ISSUE TITLE
Can't install addon to Blender 2.80 on Ubuntu

### ISSUE THREAD

**Issue by asdzxcasd** [cogitas3d/OrtogOnBlender#12]
When I open try to enable the add-on in Blender preferences I get error:
`ModuleNotFoundError: no module named 'openpyxl'`

**Comment by cogitas3d** [comment]
You have to download the last version of installer: https://drive.google.com/file/d/1rMS9yuNxan7dVfmnjxdbb9qFnPOUEFRk/view?usp=sharing

**Comment by cogitas3d** [comment]
The OrtogOnBlender doesnt run on 2.80 Blender, only in 2.78, for while.

**Comment by asdzxcasd** [comment]
Thanks for clarifying. I'll try 2.78.

I was following instructions in section "Como Instalar (Geral)". As I understand the installer that you gave link for, is Windows. Is there a Linux version?

**Comment by cogitas3d** [comment]
Sure!

http://www.ciceromoraes.com.br/doc/pt_br/OrtogOnBlender/Instalacao_Linux.html
