### ISSUE TITLE
mac problems

### ISSUE THREAD

**Issue by kceyCol** [cogitas3d/OrtogOnBlender#13]
Can´t do the smvs, openMVG nor Photogrammetry on mac. On windows works perfect.

GeraModeloFotoDef()

and

line 791 __init__.py

**Comment by cogitas3d** [comment]
Hi @kceyCol !

Please, send all output of terminal.

A big hug!

**Comment by cogitas3d** [comment]
SMVS reconstruction was removed from OrtogOnBlender
