### ISSUE TITLE
Please add a license to your repository

### ISSUE THREAD

**Issue by yarwelp** [cogitas3d/OrtogOnBlender#3]
First of all, thanks for making this Blender plugin. Very nice work :)

Please add a license to your repository that makes the code truly open source. I suggest going with the ISC license.

Here is a copy of the ISC license: https://gist.githubusercontent.com/yarwelp/84c5c986607f3e4245991480a40e2c45/raw/d998764c0e914964a380b74b28332ea0c7ca28e7/LICENSE, replace YYYY with the current year (2017), "John Doe" with your own name and john.doe@example.com with your own e-mail address (keep the angle-brackets). Alternatively if you do not wish to include your e-mail you can just remove the placeholder e-mail and angle-brackets.

**Comment by AndreaMonzini** [comment]
Actually as Blender Python Scripts it should be GPL:

"What about Add-ons or my Python scripts?
If you share or publish Python scripts – if they use the Blender API calls – have to be made available compliant to the GNU GPL as well."

Reference:
https://www.blender.org/support/faq/
