### ISSUE TITLE
Dinàmica do Mole

### ISSUE THREAD

**Issue by Guisan** [cogitas3d/OrtogOnBlender#4]
La versione disponibile su GitHub sembra incompleta. Verranno rese disponibili tutte le funzioni?
Grazie per il tuo magnifico lavoro!
-Guido Santandrea
![screenshot 80 _li](https://user-images.githubusercontent.com/17667365/34645120-6cbf6326-f345-11e7-8a20-8957b6c9e753.jpg)
![screenshot 79 _li](https://user-images.githubusercontent.com/17667365/34645122-7feafe7e-f345-11e7-95bb-0b8417777995.jpg)

**Comment by cogitas3d** [comment]
Ciao @Guisan !

Devo scrivere un tutorial cerca di questo, ma non ho tempo adesso.
Scusate :(

**Comment by Guisan** [comment]
Grazie Cicero!
Buon Lavoro :)
