### ISSUE TITLE
what smvs software should the ortgoOn plug point to

### ISSUE THREAD

**Issue by perthvr** [cogitas3d/OrtogOnBlender#5]
when I add the OrtogOn to blender what is the path to SMVS Do you have a link to SMVS on your github page.  Thanks for this project it looks like it has alot of potential
sally
![ortogosetup](https://user-images.githubusercontent.com/34245172/34753595-e0ac1634-f5f3-11e7-87ef-0025b8269c7c.png)

**Comment by cogitas3d** [comment]
Hi @perthvr !

Don't worry. Ignore this path (SMVS). I'm working to put it on Windows.

If you want use on Linux (Ubuntu), you can download the binaries here: https://drive.google.com/file/d/1TojOWgRF-D2m7NCSWO1Q2yq4_afzDXe4/view?usp=sharing

After download and unzip, you have to put the path: /home/sally/SMVS/

I hope it works well (you will have to test the binaries to see if need some library).

A big hug!

**Comment by perthvr** [comment]
obrigada   I am a linux user (beginner mode!!) so the binaries will be
useful
cheers sally
