### ISSUE TITLE
Translate this project to english

### ISSUE THREAD

**Issue by kelteseth** [cogitas3d/OrtogOnBlender#6]
This project has a tremendous potential but it's not very helpful if everything is in spanish :(

Maybe you could translate this project via https://www.deepl.com/translator ?

**Comment by cogitas3d** [comment]
Hi @kelteseth !

We are working on this, in the future the project will be in other languages.

A big hug!

**Comment by kelteseth** [comment]
Maybe then not close this issue if it's not resolved :)

**Comment by cogitas3d** [comment]
The add-on is translated to English.

**Comment by softyoda** [comment]
Is there a way to have the github readme.md and the official documentation in english ?
