### ISSUE TITLE
 register_class(...): already registered as a subclass

### ISSUE THREAD

**Issue by gerroon** [cogitas3d/OrtogOnBlender#9]
I cant enable the addon, with error below

Imported all OrtogOnBlender modules
Exception in module register(): /home/XXX/.config/blender/2.79/scripts/addons/OrtogOnBlender/__init__.py
Traceback (most recent call last):
  File "/opt/blender/2.79/scripts/modules/addon_utils.py", line 370, in enable
    mod.register()
  File "/home/XXX/.config/blender/2.79/scripts/addons/OrtogOnBlender/__init__.py", line 2038, in register
    bpy.utils.register_class(CriaSplint)
ValueError: register_class(...): already registered as a subclass

**Comment by cogitas3d** [comment]
Hi @gerroon !

Whas OS do you use?

**Comment by gerroon** [comment]
I am on Linux Debian Buster, I had to install bunch of pip packs to get it working though.

**Comment by cogitas3d** [comment]
1) You can follow this tutorial: http://www.ciceromoraes.com.br/doc/pt_br/OrtogOnBlender/Instalacao_Linux.html

2) You can try to use Linux3DCS: http://www.ciceromoraes.com.br/doc/pt_br/OrtogOnBlender/Instalacao_Linux3DCS.html

**Comment by gerroon** [comment]
thanks I will take a look at them
